"""Check test results and coverage from JUnit XML and Coverage XML generated by pytest"""
from pycobertura import Cobertura
from junitparser import JUnitXml
import sys
from pathlib import Path
import tomllib
from typing import Union

from .models.checkresults import (
    TestResultPath, TestPassRate, JunitResult, CoverageResult, TestResultSummary
)


class CheckTestingResults:

    @staticmethod
    def _load_test_report_paths() -> TestResultPath:
        """Read [tool.test-report-paths] from pyproject.toml (single source of truth)."""
        root = Path(__file__).resolve().parent.parent
        pyproject_path = root.joinpath("pyproject.toml")
        if not pyproject_path.exists():
            raise FileNotFoundError(f"pyproject.toml not found in {root}")
    
        with open(pyproject_path, "rb") as f:
            pyproject_config = tomllib.load(f)
        
        report_paths = pyproject_config.get("tool", {}).get("test-report-paths", {})
        for key, value in report_paths.items():
            report_paths[key] = root.joinpath(value)
        
        if 'junit_xml' not in report_paths:
            raise ValueError("No JUnit XML path (junit_xml) found in pyproject.toml")
        if 'coverage_xml' not in report_paths:
            raise ValueError("No Coverage XML path (coverage_xml) found in pyproject.toml")

        return TestResultPath(
            junit_xml=report_paths["junit_xml"],
            junit_html=report_paths["junit_html"],
            coverage_xml=report_paths["coverage_xml"],
            coverage_html=report_paths["coverage_html"]
        )
    
    @staticmethod
    def _load_test_pass_rate() -> TestPassRate:
        root = Path(__file__).resolve().parent.parent
        pyproject_path = root.joinpath("pyproject.toml")
        if not pyproject_path.exists():
            raise FileNotFoundError(f"pyproject.toml not found in {root}")
    
        with open(pyproject_path, "rb") as f:
            pyproject_config = tomllib.load(f)
        
        test_pass_rate = pyproject_config.get("tool", {}).get("test-pass-rate", {})
        if 'pass_rate' not in test_pass_rate:
            raise ValueError("No pass rate (pass_rate) found in pyproject.toml")
        if 'cov_line_rate' not in test_pass_rate:
            raise ValueError("No line rate (cov_line_rate) found in pyproject.toml")
        if 'cov_branch_rate' not in test_pass_rate:
            raise ValueError("No branch rate (cov_branch_rate) found in pyproject.toml")
        
        return TestPassRate(
            pass_rate=test_pass_rate["pass_rate"],
            cov_line_rate=test_pass_rate["cov_line_rate"],
            cov_branch_rate=test_pass_rate["cov_branch_rate"]
        )


    @staticmethod
    def _check_junit_xml(junit_xml_path: Union[str, Path]) -> JunitResult:

        junit_xml = JUnitXml.fromfile(junit_xml_path)
        suites, errors, failures, tests = 0, 0, 0, 0
        for suite in junit_xml:
            suites += 1
            errors += suite.errors
            failures += suite.failures
            tests += suite.tests
        
        pass_rate = 1 - (errors + failures) / tests

        return JunitResult(
            suites=suites,
            tests=tests,
            errors=errors,
            failures=failures,
            pass_rate=pass_rate
        )

    @staticmethod
    def _check_coverage_xml(coverage_xml_path: Union[str, Path]) -> CoverageResult:

        coverage = Cobertura(coverage_xml_path)
        line_rate = coverage.line_rate()
        branch_rate = coverage.branch_rate()
        
        return CoverageResult(line_rate=line_rate, branch_rate=branch_rate)


if __name__ == "__main__":

    testing_result_paths = CheckTestingResults._load_test_report_paths()
    testing_pass_rate = CheckTestingResults._load_test_pass_rate()

    junit_result = CheckTestingResults._check_junit_xml(testing_result_paths.junit_xml)
    coverage_result = CheckTestingResults._check_coverage_xml(testing_result_paths.coverage_xml)

    test_result_summary = TestResultSummary(
        test_pass_rate=testing_pass_rate,
        junit_result=junit_result,
        coverage_result=coverage_result
    )

    print(test_result_summary.model_dump_json(indent=4))

    if test_result_summary.pass_ind: sys.exit(0)
    else: sys.exit(1)