# Reusable action: compute next semver from latest v* tag (0.0.99→0.1.0, 0.99.99→1.0.0).
# Requires: repo already checked out with fetch-depth: 0 so git tag -l sees all tags.
name: Compute next version
description: Get latest v* tag and compute next version (patch+1, rollover at 99)
outputs:
  version:
    description: Next version string (e.g. 0.0.1)
    value: ${{ steps.compute.outputs.version }}
  tag:
    description: Next tag with prefix (e.g. v0.0.1)
    value: ${{ steps.compute.outputs.tag }}
inputs:
  prefix:
    description: Tag prefix (default v)
    required: false
    default: v
runs:
  using: composite
  steps:
    - id: compute
      shell: bash
      run: |
        
        PREFIX="${{ inputs.prefix }}"
        LATEST=$(git tag -l "${PREFIX}*" --sort=-v:refname | grep -E "^${PREFIX}[0-9]+\.[0-9]+\.[0-9]+$" || true | head -1)
        if [ -z "$LATEST" ]; then
          VERSION="0.0.0"
        else
          VER="${LATEST#$PREFIX}"
          MAJOR="${VER%%.*}"
          REST="${VER#*.}"
          MINOR="${REST%%.*}"
          PATCH="${REST#*.}"
          PATCH=$((PATCH + 1))
          if [ "$PATCH" -gt 99 ]; then
            PATCH=0
            MINOR=$((MINOR + 1))
            if [ "$MINOR" -gt 99 ]; then
              MINOR=0
              MAJOR=$((MAJOR + 1))
            fi
          fi
          VERSION="$MAJOR.$MINOR.$PATCH"
        fi
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=${PREFIX}${VERSION}" >> $GITHUB_OUTPUT
